# Settings and configurations that are common for all containers
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: webhook-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    volumes:
      - ./runtime/deploy/data/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
